#!/usr/bin/env bash
set -euo pipefail

VERSION="1.0.0"

log(){ echo -e "\033[1;32m[OK]\033[0m $*"; }
warn(){ echo -e "\033[1;33m[WARN]\033[0m $*"; }
err(){ echo -e "\033[1;31m[ERR]\033[0m $*" >&2; }

usage(){
  cat <<'EOF'
Install Static IPv4/IPv6 on Ubuntu 20.04/24.04 (netplan) + Lockdown auto IP changes.

Usage:
  sudo ./install-static-ip.sh \
    --iface ens3 \
    --ipv4 192.168.1.10/24 --gw4 192.168.1.1 \
    --ipv6 2001:db8::10/64 --gw6 2001:db8::1 \
    --dns "223.5.5.5,114.114.114.114,2400:3200::1,2402:4e00::" \
    [--netplan-file /etc/netplan/01-static-ip.yaml] \
    [--keep-networkmanager] \
    [--no-cloud-init] \
    [--dry-run] \
    [--yes]

Options:
  --iface IFACE              Interface name (e.g. ens3/eth0)
  --ipv4 CIDR                Static IPv4 CIDR (e.g. 192.168.1.10/24)
  --gw4 GW                    IPv4 default gateway
  --ipv6 CIDR                Static IPv6 CIDR (e.g. 2001:db8::10/64)
  --gw6 GW                    IPv6 default gateway
  --dns LIST                 Comma-separated DNS for v4/v6 (optional)
  --netplan-file PATH        Netplan output file (default: /etc/netplan/01-static-ip.yaml)
  --keep-networkmanager      Do NOT disable/mask NetworkManager (default: disable to reduce interference)
  --no-cloud-init            Do NOT write cloud-init disable file (default: write it)
  --dry-run                  Print changes without applying
  --yes                      Non-interactive (skip confirmation)
  -h, --help                 Show help
  -v, --version              Show version

Notes:
  - This may cut off your SSH connection. Prefer console/out-of-band access.
  - Backups are created with .bak.TIMESTAMP suffix.
EOF
}

need_root(){
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "Please run as root (use sudo)."
    exit 1
  fi
}

cmd_exists(){ command -v "$1" >/dev/null 2>&1; }

backup_file(){
  local f="$1"
  if [[ -e "$f" ]]; then
    local ts; ts="$(date +%Y%m%d_%H%M%S)"
    cp -a "$f" "${f}.bak.${ts}"
    log "Backup: $f -> ${f}.bak.${ts}"
  fi
}

backup_dir(){
  local d="$1"
  if [[ -d "$d" ]]; then
    local ts; ts="$(date +%Y%m%d_%H%M%S)"
    cp -a "$d" "${d}.bak.${ts}"
    log "Backup dir: $d -> ${d}.bak.${ts}"
  fi
}

get_default_iface(){
  local iface=""
  iface="$(ip -o route show default 2>/dev/null | awk '{print $5; exit}')"
  if [[ -z "$iface" ]]; then
    iface="$(ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$' | head -n1 || true)"
  fi
  echo "$iface"
}

trim_csv_to_yaml_list(){
  # Input: "1.1.1.1, 8.8.8.8, 2400::1" -> "[1.1.1.1, 8.8.8.8, 2400::1]"
  local s="${1:-}"
  s="$(echo "$s" | tr -d '\n' | sed 's/[[:space:]]//g' | sed 's/,,*/,/g' | sed 's/^,//; s/,$//')"
  if [[ -z "$s" ]]; then
    echo "[]"
    return 0
  fi
  # split and re-join with ", "
  echo "$s" | tr ',' '\n' | awk 'NF{print $0}' | paste -sd, - | sed 's/,/, /g' | awk '{print "[" $0 "]"}'
}

write_sysctl_lockdown(){
  local f="/etc/sysctl.d/99-static-ip-lockdown.conf"
  backup_file "$f"
  cat >"$f" <<'EOF'
# Prevent automatic IPv6 address/route changes via RA/SLAAC
net.ipv6.conf.all.accept_ra=0
net.ipv6.conf.default.accept_ra=0
net.ipv6.conf.all.autoconf=0
net.ipv6.conf.default.autoconf=0
net.ipv6.conf.all.use_tempaddr=0
net.ipv6.conf.default.use_tempaddr=0
EOF
  sysctl --system >/dev/null 2>&1 || true
  log "Wrote sysctl lockdown: $f"
}

disable_cloud_init_network(){
  local d="/etc/cloud/cloud.cfg.d"
  mkdir -p "$d"
  local f="$d/99-disable-network-config.cfg"
  backup_file "$f"
  cat >"$f" <<'EOF'
# Disable cloud-init network configuration to prevent IP changes
network: {config: disabled}
EOF
  log "Disabled cloud-init network takeover: $f"
}

enable_networkd(){
  systemctl enable systemd-networkd.service >/dev/null 2>&1 || true
  systemctl start systemd-networkd.service  >/dev/null 2>&1 || true
  log "systemd-networkd enabled."
}

disable_networkmanager(){
  if systemctl list-unit-files | grep -q '^NetworkManager\.service'; then
    systemctl stop NetworkManager.service 2>/dev/null || true
    systemctl disable NetworkManager.service 2>/dev/null || true
    systemctl mask NetworkManager.service 2>/dev/null || true
    warn "NetworkManager disabled/masked."
  fi
}

disable_dhcp_clients_best_effort(){
  for u in dhclient.service dhclient@.service isc-dhcp-client.service; do
    if systemctl list-unit-files | awk '{print $1}' | grep -qx "$u"; then
      systemctl stop "$u" 2>/dev/null || true
      systemctl disable "$u" 2>/dev/null || true
      systemctl mask "$u" 2>/dev/null || true
      warn "DHCP client service disabled: $u"
    fi
  done
}

render_netplan(){
  local iface="$1"
  local ipv4="$2"
  local gw4="$3"
  local ipv6="$4"
  local gw6="$5"
  local dns_list="$6"
  local out="$7"

  backup_dir "/etc/netplan"
  backup_file "$out"

  cat >"$out" <<EOF
# Generated by install-static-ip.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    ${iface}:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      addresses:
        - ${ipv4}
        - ${ipv6}
      routes:
        - to: default
          via: ${gw4}
        - to: default
          via: ${gw6}
      nameservers:
        addresses: ${dns_list}
EOF

  chmod 600 "$out"
  log "Wrote netplan: $out"
}

apply_netplan(){
  if ! cmd_exists netplan; then
    err "netplan not found. This script targets Ubuntu 20.04/24.04."
    exit 1
  fi
  netplan generate
  netplan apply
  log "netplan applied."
}

show_status(){
  echo
  echo "====== Current addr/route summary ======"
  ip -br addr || true
  echo
  ip -4 route show default || true
  ip -6 route show default || true
  echo "======================================="
  echo
}

confirm_or_exit(){
  local yes="${1:-false}"
  if [[ "$yes" == "true" ]]; then return 0; fi
  echo
  warn "This will reconfigure networking and may disconnect SSH."
  read -r -p "Continue? [y/N]: " ans || true
  case "${ans:-}" in
    y|Y|yes|YES) return 0 ;;
    *) err "Aborted."; exit 2 ;;
  esac
}

# -------------------- args --------------------
IFACE=""
IPV4=""
GW4=""
IPV6=""
GW6=""
DNS=""
NETPLAN_FILE="/etc/netplan/01-static-ip.yaml"
KEEP_NM="false"
NO_CLOUD_INIT="false"
DRY_RUN="false"
YES="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --iface) IFACE="${2:-}"; shift 2;;
    --ipv4) IPV4="${2:-}"; shift 2;;
    --gw4)  GW4="${2:-}"; shift 2;;
    --ipv6) IPV6="${2:-}"; shift 2;;
    --gw6)  GW6="${2:-}"; shift 2;;
    --dns)  DNS="${2:-}"; shift 2;;
    --netplan-file) NETPLAN_FILE="${2:-}"; shift 2;;
    --keep-networkmanager) KEEP_NM="true"; shift 1;;
    --no-cloud-init) NO_CLOUD_INIT="true"; shift 1;;
    --dry-run) DRY_RUN="true"; shift 1;;
    --yes) YES="true"; shift 1;;
    -h|--help) usage; exit 0;;
    -v|--version) echo "$VERSION"; exit 0;;
    *) err "Unknown arg: $1"; usage; exit 1;;
  esac
done

need_root

if [[ -z "$IFACE" ]]; then IFACE="$(get_default_iface)"; fi

# Basic validation
[[ -n "$IFACE" ]] || { err "--iface is required (or system default route iface)."; exit 1; }
[[ -n "$IPV4"  ]] || { err "--ipv4 is required."; exit 1; }
[[ -n "$GW4"   ]] || { err "--gw4 is required."; exit 1; }
[[ -n "$IPV6"  ]] || { err "--ipv6 is required."; exit 1; }
[[ -n "$GW6"   ]] || { err "--gw6 is required."; exit 1; }

DNS_LIST="$(trim_csv_to_yaml_list "$DNS")"

echo "Plan:"
echo "  iface        : $IFACE"
echo "  ipv4/gw4     : $IPV4  via $GW4"
echo "  ipv6/gw6     : $IPV6  via $GW6"
echo "  dns          : $DNS_LIST"
echo "  netplan file : $NETPLAN_FILE"
echo "  cloud-init   : $([[ "$NO_CLOUD_INIT" == "true" ]] && echo "unchanged" || echo "disable network takeover")"
echo "  NetworkManager: $([[ "$KEEP_NM" == "true" ]] && echo "keep" || echo "disable/mask")"
echo "  dry-run      : $DRY_RUN"
echo

confirm_or_exit "$YES"

if [[ "$DRY_RUN" == "true" ]]; then
  warn "Dry-run: will not change anything. Showing the netplan YAML that would be written:"
  cat <<EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    ${IFACE}:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      addresses:
        - ${IPV4}
        - ${IPV6}
      routes:
        - to: default
          via: ${GW4}
        - to: default
          via: ${GW6}
      nameservers:
        addresses: ${DNS_LIST}
EOF
  exit 0
fi

# Lockdown steps
write_sysctl_lockdown
if [[ "$NO_CLOUD_INIT" != "true" ]]; then
  disable_cloud_init_network
fi

enable_networkd
if [[ "$KEEP_NM" != "true" ]]; then
  disable_networkmanager
fi
disable_dhcp_clients_best_effort

# Netplan
render_netplan "$IFACE" "$IPV4" "$GW4" "$IPV6" "$GW6" "$DNS_LIST" "$NETPLAN_FILE"
apply_netplan
show_status

log "Done."
warn "If something went wrong, restore backups under /etc/netplan/*.bak.* and re-apply netplan."
